//! API keys: who a request speaks for.
//!
//! Every user gets one key when they are created, and it is shown once, in
//! the response that created them. A request proves who it is with
//! `Authorization: Bearer <key>` (or `X-Api-Key: <key>`); market data needs
//! no key, but nothing that belongs to a user — their traders, orders,
//! accounts or money — moves without one.
//!
//! Authentication and persistence retain SHA-256 digests and nothing else.
//! A key exists in full exactly once — in the response that created the user
//! — and is never held by the keyring, written to the journal or saved. A
//! client that loses that response cannot have the key back; it asks for a
//! new user.

use std::collections::BTreeMap;

use crate::account::UserId;
use sha2::{Digest, Sha256};

/// Bytes of entropy behind a key: 128 bits, as 32 hex characters.
const KEY_BYTES: usize = 16;

/// What every key starts with, so one is recognisable in a log or a config.
pub const KEY_PREFIX: &str = "fehu_";

/// A new key: [`KEY_PREFIX`] and 32 hex characters of operating-system
/// entropy. Panics only if the OS cannot produce randomness at all, which is
/// not a condition to serve traffic in.
pub fn new_api_key() -> String {
    let mut bytes = [0u8; KEY_BYTES];
    getrandom::fill(&mut bytes).expect("the operating system has randomness");
    let mut key = String::with_capacity(KEY_PREFIX.len() + KEY_BYTES * 2);
    key.push_str(KEY_PREFIX);
    for b in bytes {
        use std::fmt::Write as _;
        let _ = write!(key, "{b:02x}");
    }
    key
}

/// The digests of the keys the server has issued, and the user each one
/// speaks for.
///
/// No credential is ever held here. A key is generated by the route that
/// creates the user, returned once in that response, and reaches the keyring
/// only as [`key_digest`] — which is also what the journal and the save file
/// carry, so neither is a list of live credentials.
#[derive(Clone, Default)]
pub struct Keyring {
    by_key: BTreeMap<String, UserId>,
    by_user: BTreeMap<UserId, String>,
}

/// Domain-separated SHA-256 of a randomly generated bearer credential.
/// This is for high-entropy API keys, not user-chosen passwords.
pub(crate) fn key_digest(key: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(b"fehu-api-key-v1\0");
    hasher.update(key.as_bytes());
    let mut digest = String::from("sha256:");
    for byte in hasher.finalize() {
        use std::fmt::Write as _;
        let _ = write!(digest, "{byte:02x}");
    }
    digest
}

impl std::fmt::Debug for Keyring {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Keyring")
            .field("len", &self.len())
            .finish_non_exhaustive()
    }
}

impl Keyring {
    /// Let `user` be spoken for by the key behind `digest`, retiring any
    /// earlier one.
    pub fn install(&mut self, user: UserId, digest: String) {
        if let Some(old) = self.by_user.insert(user, digest.clone()) {
            self.by_key.remove(&old);
        }
        self.by_key.insert(digest, user);
    }

    /// Generate a key for `user`, install its digest, and hand the key back.
    /// The caller holds the only copy from here on.
    pub fn issue(&mut self, user: UserId) -> String {
        let key = new_api_key();
        self.install(user, key_digest(&key));
        key
    }

    /// The user `key` speaks for, if it is one of ours.
    pub fn user_of(&self, key: &str) -> Option<UserId> {
        self.by_key.get(&key_digest(key)).copied()
    }

    /// SHA-256 digests as `(digest, user id)` pairs, for a save file.
    pub fn pairs(&self) -> Vec<(String, u64)> {
        self.by_key.iter().map(|(k, u)| (k.clone(), u.0)).collect()
    }

    /// Rebuild a keyring from what [`Keyring::pairs`] wrote down, so a
    /// player's key still opens their account after a restart.
    pub fn from_pairs(pairs: impl IntoIterator<Item = (String, u64)>) -> Self {
        let mut keys = Self::default();
        for (digest, user) in pairs {
            keys.install(UserId(user), digest);
        }
        keys
    }

    /// Number of keys issued.
    pub fn len(&self) -> usize {
        self.by_key.len()
    }

    pub fn is_empty(&self) -> bool {
        self.by_key.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn keys_are_unique_and_resolve_to_their_user() {
        let mut keys = Keyring::default();
        let one = keys.issue(UserId(1));
        let two = keys.issue(UserId(2));
        assert_ne!(one, two, "every key is its own");
        assert!(one.starts_with(KEY_PREFIX));
        assert_eq!(one.len(), KEY_PREFIX.len() + KEY_BYTES * 2);
        assert!(
            one[KEY_PREFIX.len()..]
                .chars()
                .all(|c| c.is_ascii_hexdigit()),
            "{one}"
        );
        assert_eq!(keys.user_of(&one), Some(UserId(1)));
        assert_eq!(keys.user_of(&two), Some(UserId(2)));
        assert_eq!(keys.user_of("fehu_nope"), None);
        assert_eq!(keys.len(), 2);
    }

    #[test]
    fn a_keyring_round_trips_through_its_pairs() {
        let mut keys = Keyring::default();
        let one = keys.issue(UserId(1));
        let two = keys.issue(UserId(7));
        let back = Keyring::from_pairs(keys.pairs());
        assert_eq!(back.user_of(&one), Some(UserId(1)));
        assert_eq!(back.user_of(&two), Some(UserId(7)));
        assert_eq!(back.len(), 2);
    }

    #[test]
    fn the_keyring_never_holds_a_credential() {
        let mut keys = Keyring::default();
        let key = keys.issue(UserId(1));
        let pairs = keys.pairs();
        assert_ne!(pairs[0].0, key);
        assert!(pairs[0].0.starts_with("sha256:"));
        assert_eq!(keys.user_of(&pairs[0].0), None);
        assert!(!format!("{keys:?}").contains(&key));
        assert_eq!(keys.user_of(&key), Some(UserId(1)));
        let mut restored = Keyring::from_pairs(pairs);
        let replacement = restored.issue(UserId(1));
        assert_eq!(restored.user_of(&key), None);
        assert_eq!(restored.user_of(&replacement), Some(UserId(1)));
        assert_eq!(restored.len(), 1);
    }

    #[test]
    fn a_digest_can_be_installed_without_the_key_that_made_it() {
        let mut keys = Keyring::default();
        let key = new_api_key();
        keys.install(UserId(4), key_digest(&key));
        assert_eq!(keys.user_of(&key), Some(UserId(4)));
        assert_eq!(keys.len(), 1);
    }

    #[test]
    fn re_issuing_retires_the_old_key() {
        let mut keys = Keyring::default();
        let old = keys.issue(UserId(1));
        let new = keys.issue(UserId(1));
        assert_eq!(keys.user_of(&old), None, "the old key stops working");
        assert_eq!(keys.user_of(&new), Some(UserId(1)));
        assert_eq!(keys.len(), 1);
    }
}
