//! A limit order book with price–time priority.
//!
//! Prices are whole cents, quantities are shares. The book is deterministic:
//! orders match in the order they arrive, resting orders at one price fill
//! first-in first-out, and ids are assigned sequentially. It knows nothing
//! about the price process; [`Exchange`](crate::Exchange) composes the two.

use alloc::boxed::Box;
use alloc::collections::{BTreeMap, VecDeque};
use alloc::vec::Vec;
use core::fmt;

use crate::time::Timestamp;

/// Buy or sell.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[cfg_attr(
    feature = "serde",
    derive(serde::Serialize, serde::Deserialize),
    serde(rename_all = "snake_case")
)]
pub enum Side {
    /// Bid.
    Buy,
    /// Ask.
    Sell,
}

impl Side {
    /// The other side.
    #[must_use]
    pub const fn opposite(self) -> Side {
        match self {
            Self::Buy => Self::Sell,
            Self::Sell => Self::Buy,
        }
    }

    /// `+1` for a buy, `−1` for a sell.
    #[must_use]
    pub const fn sign(self) -> i64 {
        match self {
            Self::Buy => 1,
            Self::Sell => -1,
        }
    }
}

/// Identifies a trader (a player, or an NPC the game controls). Trades by a
/// trader move the reference price; synthetic liquidity does not.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(transparent))]
pub struct TraderId(pub u64);

/// Who placed an order.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[cfg_attr(
    feature = "serde",
    derive(serde::Serialize, serde::Deserialize),
    serde(rename_all = "snake_case")
)]
pub enum Owner {
    /// Liquidity generated by the exchange: the maker ladder and the prints
    /// that realise the simulator's volume.
    Synthetic,
    /// A trader.
    Trader(TraderId),
}

impl Owner {
    /// The trader, if this is not synthetic.
    #[must_use]
    pub const fn trader(self) -> Option<TraderId> {
        match self {
            Self::Synthetic => None,
            Self::Trader(id) => Some(id),
        }
    }
}

/// Sequential order id assigned by the book. `OrderId::HIDDEN` (zero) marks
/// the exchange's hidden liquidity and is never a real order.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(transparent))]
pub struct OrderId(pub u64);

impl OrderId {
    /// The counterparty of a synthetic print that exhausted the visible book.
    pub const HIDDEN: OrderId = OrderId(0);
}

/// Market or limit.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[cfg_attr(
    feature = "serde",
    derive(serde::Serialize, serde::Deserialize),
    serde(tag = "type", rename_all = "snake_case")
)]
pub enum OrderKind {
    /// Take whatever is available. Never rests; a `Gtc` market order behaves
    /// as `Ioc`.
    Market,
    /// Fill at `price_cents` or better; the remainder may rest.
    Limit {
        /// Limit price in cents, `≥ 1`.
        price_cents: i64,
    },
}

/// What to do with the part of an order that does not fill immediately.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
#[cfg_attr(
    feature = "serde",
    derive(serde::Serialize, serde::Deserialize),
    serde(rename_all = "snake_case")
)]
pub enum TimeInForce {
    /// Good till cancelled: the remainder rests in the book.
    #[default]
    Gtc,
    /// Immediate or cancel: the remainder is dropped.
    Ioc,
    /// Fill or kill: either the whole quantity fills immediately or nothing
    /// happens.
    Fok,
}

/// An order to submit.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Order {
    /// Who is placing it.
    pub owner: Owner,
    /// Buy or sell.
    pub side: Side,
    /// Market or limit.
    pub kind: OrderKind,
    /// Time in force.
    pub tif: TimeInForce,
    /// Shares, `[1, 10^12]`.
    pub qty: u64,
}

impl Order {
    /// A limit order, good till cancelled.
    #[must_use]
    pub const fn limit(owner: Owner, side: Side, price_cents: i64, qty: u64) -> Self {
        Self {
            owner,
            side,
            kind: OrderKind::Limit { price_cents },
            tif: TimeInForce::Gtc,
            qty,
        }
    }

    /// A market order.
    #[must_use]
    pub const fn market(owner: Owner, side: Side, qty: u64) -> Self {
        Self {
            owner,
            side,
            kind: OrderKind::Market,
            tif: TimeInForce::Ioc,
            qty,
        }
    }

    /// Same order with a different time in force.
    #[must_use]
    pub const fn with_tif(self, tif: TimeInForce) -> Self {
        Self { tif, ..self }
    }
}

/// Largest accepted order quantity.
pub const MAX_ORDER_QTY: u64 = 1_000_000_000_000;
/// Largest accepted limit price, in cents.
pub const MAX_PRICE_CENTS: i64 = 1_000_000_000_000_000;

/// Why an [`Order`] was rejected.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub enum OrderError {
    /// `qty` is zero.
    ZeroQuantity,
    /// `qty` exceeds [`MAX_ORDER_QTY`].
    QuantityTooLarge,
    /// `qty` is not a whole number of the symbol's lots.
    OddLot,
    /// A limit price outside `[1, 10^15]`.
    BadPrice,
    /// A limit price that is not on the symbol's tick grid.
    OffTick,
    /// No further unique order ids can be assigned.
    IdExhausted,
    /// Synthetic orders are managed by the exchange; give NPCs a `TraderId`.
    SyntheticOwner,
}

impl fmt::Display for OrderError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::ZeroQuantity => "order quantity must be at least 1",
            Self::QuantityTooLarge => "order quantity is too large",
            Self::OddLot => "order quantity must be a whole number of lots",
            Self::BadPrice => "limit price must be in [1, 10^15] cents",
            Self::OffTick => "limit price must be a whole number of ticks",
            Self::IdExhausted => "order id space is exhausted",
            Self::SyntheticOwner => "synthetic orders cannot be submitted directly",
        })
    }
}

#[cfg(feature = "std")]
impl std::error::Error for OrderError {}

/// What a symbol will quote and trade in.
///
/// A real venue does not accept every price and every size: it quotes in
/// ticks and trades in lots, so that the book has a manageable number of
/// price levels and a size means something. Both default to the finest
/// possible — one cent, one share — which constrains nothing and is what the
/// sample market runs with unless it is told otherwise.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct MarketRules {
    /// Prices must be a whole number of these cents. `1` allows every cent.
    pub tick_cents: i64,
    /// Quantities must be a whole number of these shares. `1` allows every
    /// share.
    pub lot: u64,
}

impl Default for MarketRules {
    fn default() -> Self {
        Self {
            tick_cents: 1,
            lot: 1,
        }
    }
}

impl MarketRules {
    /// Whether `price_cents` sits on the tick grid.
    #[must_use]
    pub fn allows_price(&self, price_cents: i64) -> bool {
        self.tick_cents <= 1 || price_cents % self.tick_cents == 0
    }

    /// Whether `qty` is a whole number of lots.
    #[must_use]
    pub fn allows_qty(&self, qty: u64) -> bool {
        self.lot <= 1 || qty.is_multiple_of(self.lot)
    }

    /// `price_cents` rounded down to the tick, never below one tick: a price
    /// of zero is not a price.
    #[must_use]
    pub fn floor_price(&self, price_cents: i64) -> i64 {
        if self.tick_cents <= 1 {
            return price_cents;
        }
        let floored = price_cents - price_cents.rem_euclid(self.tick_cents);
        floored.max(self.tick_cents)
    }

    /// `price_cents` rounded up to the tick.
    #[must_use]
    pub fn ceil_price(&self, price_cents: i64) -> i64 {
        if self.tick_cents <= 1 {
            return price_cents;
        }
        let up = price_cents.saturating_add(self.tick_cents - 1);
        self.floor_price(up)
    }

    /// `qty` rounded down to whole lots. Zero when it does not reach one:
    /// the caller decides whether that means "skip" or "refuse".
    #[must_use]
    pub fn floor_qty(&self, qty: u64) -> u64 {
        if self.lot <= 1 {
            return qty;
        }
        qty - qty % self.lot
    }
}

/// Why a cancel failed.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub enum CancelError {
    /// No resting order with that id (it may have filled).
    Unknown,
    /// The order belongs to someone else.
    NotOwner,
}

impl fmt::Display for CancelError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::Unknown => "no resting order with that id",
            Self::NotOwner => "order belongs to another trader",
        })
    }
}

#[cfg(feature = "std")]
impl std::error::Error for CancelError {}

/// An order resting in the book.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Resting {
    /// Book-assigned id.
    pub id: OrderId,
    /// Who placed it.
    pub owner: Owner,
    /// Buy or sell.
    pub side: Side,
    /// Limit price.
    pub price_cents: i64,
    /// Original quantity.
    pub qty: u64,
    /// Quantity still open.
    pub remaining: u64,
    /// When it was placed.
    pub ts: Timestamp,
}

/// One side of a trade.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Party {
    /// The order involved.
    pub order: OrderId,
    /// Its owner.
    pub owner: Owner,
}

/// One execution. The taker is the incoming order; the maker was resting and
/// sets the price.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Trade {
    /// When it happened.
    pub ts: Timestamp,
    /// Execution price (the maker's limit).
    pub price_cents: i64,
    /// Shares.
    pub qty: u64,
    /// Side of the taker.
    pub taker_side: Side,
    /// The incoming order.
    pub taker: Party,
    /// The resting order.
    pub maker: Party,
}

impl Trade {
    /// Signed shares transferred to `trader` (`+` bought, `−` sold), zero if
    /// the trader is not a party or is both parties.
    #[must_use]
    pub fn signed_qty_for(&self, trader: TraderId) -> i64 {
        let owner = Owner::Trader(trader);
        let q = i64::try_from(self.qty).unwrap_or(i64::MAX);
        let mut s = 0;
        if self.taker.owner == owner {
            s += self.taker_side.sign() * q;
        }
        if self.maker.owner == owner {
            s += self.taker_side.opposite().sign() * q;
        }
        s
    }

    /// Net signed shares moved from synthetic liquidity to traders (`+` when
    /// a trader bought from the exchange). Trader-to-trader trades net to
    /// zero.
    #[must_use]
    pub fn trader_flow(&self) -> i64 {
        let q = i64::try_from(self.qty).unwrap_or(i64::MAX);
        match (self.taker.owner, self.maker.owner) {
            (Owner::Trader(_), Owner::Synthetic) => self.taker_side.sign() * q,
            (Owner::Synthetic, Owner::Trader(_)) => self.taker_side.opposite().sign() * q,
            _ => 0,
        }
    }
}

/// Aggregated depth at one price.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Level {
    /// Price in cents.
    pub price_cents: i64,
    /// Total open quantity.
    pub qty: u64,
    /// Number of resting orders.
    pub orders: u32,
}

/// Final state of a submitted order.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[cfg_attr(
    feature = "serde",
    derive(serde::Serialize, serde::Deserialize),
    serde(rename_all = "snake_case")
)]
pub enum OrderStatus {
    /// Fully executed.
    Filled,
    /// Partly or not at all executed; the remainder rests in the book.
    Resting,
    /// The unexecuted remainder was dropped (`Ioc`, `Fok`, or a market
    /// order that ran out of liquidity).
    Cancelled,
}

/// What happened to a submitted order.
#[derive(Clone, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Placement {
    /// The id assigned to the order.
    pub id: OrderId,
    /// Executions, in order.
    pub trades: Vec<Trade>,
    /// Shares executed.
    pub filled: u64,
    /// Shares not executed (resting or cancelled).
    pub remaining: u64,
    /// Where the remainder went.
    pub status: OrderStatus,
}

impl Placement {
    /// Total cents paid or received, saturating.
    #[must_use]
    pub fn notional_cents(&self) -> i64 {
        self.trades.iter().fold(0i64, |acc, t| {
            acc.saturating_add(notional(t.price_cents, t.qty))
        })
    }

    /// Volume-weighted average execution price, if anything filled.
    #[must_use]
    pub fn avg_price_cents(&self) -> Option<f64> {
        if self.filled == 0 {
            return None;
        }
        let sum: f64 = self
            .trades
            .iter()
            .map(|t| t.price_cents as f64 * t.qty as f64)
            .sum();
        Some(sum / self.filled as f64)
    }
}

/// What a hypothetical order would execute against the current book.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Preview {
    /// Shares that would execute.
    pub filled: u64,
    /// Cents that would change hands, saturating.
    pub notional_cents: i64,
    /// Worst price that would be paid or received.
    pub worst_price_cents: Option<i64>,
}

pub(crate) fn notional(price_cents: i64, qty: u64) -> i64 {
    let n = i128::from(price_cents) * i128::from(qty);
    i64::try_from(n).unwrap_or(i64::MAX)
}

/// The book. See the [module docs](self).
#[derive(Clone, Debug, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct OrderBook {
    /// Keyed by price; the best bid is the last key.
    bids: BTreeMap<i64, VecDeque<Resting>>,
    /// Keyed by price; the best ask is the first key.
    asks: BTreeMap<i64, VecDeque<Resting>>,
    /// Every resting order's side and price, for cancels and lookups.
    index: BTreeMap<OrderId, (Side, i64)>,
    next_id: u64,
    /// The tick and lot this book enforces. Not serialised: the exchange
    /// owns the truth in its [`TradingParams`](crate::TradingParams) and
    /// sets it here whenever a book is assembled, so the two cannot drift.
    #[cfg_attr(feature = "serde", serde(skip))]
    rules: MarketRules,
}

impl Default for OrderBook {
    fn default() -> Self {
        Self::new()
    }
}

impl OrderBook {
    /// An empty book. Ids start at 1.
    #[must_use]
    pub fn new() -> Self {
        Self {
            bids: BTreeMap::new(),
            asks: BTreeMap::new(),
            index: BTreeMap::new(),
            next_id: 1,
            rules: MarketRules::default(),
        }
    }

    /// The id that the next accepted submission will receive.
    #[must_use]
    pub fn next_order_id(&self) -> OrderId {
        OrderId(self.next_id)
    }

    /// Skip unused ids below `minimum`. Never moves the counter backwards.
    /// Coordinators can use this to allocate trader ids across several books.
    pub fn advance_order_id(&mut self, minimum: OrderId) {
        self.next_id = self.next_id.max(minimum.0);
    }

    /// Check structural invariants, including indexes, price queues, quantities
    /// and the next id. Useful after deserializing a book from external storage.
    /// Returns the first broken invariant without changing the book.
    pub fn validate_state(&self) -> Result<(), &'static str> {
        if self.next_id == 0 || self.next_id == u64::MAX {
            return Err("next order id is zero or exhausted");
        }
        let mut expected = BTreeMap::new();
        for (side, levels) in [(Side::Buy, &self.bids), (Side::Sell, &self.asks)] {
            for (&price, queue) in levels {
                if !(1..=MAX_PRICE_CENTS).contains(&price) || queue.is_empty() {
                    return Err("price level is invalid or empty");
                }
                let mut previous = 0;
                let mut total = 0u64;
                for order in queue {
                    if order.side != side || order.price_cents != price {
                        return Err("resting order does not match its price level");
                    }
                    if order.id.0 <= previous || order.id.0 >= self.next_id {
                        return Err("order ids violate queue priority or the next id");
                    }
                    previous = order.id.0;
                    if order.qty == 0
                        || order.qty > MAX_ORDER_QTY
                        || order.remaining == 0
                        || order.remaining > order.qty
                    {
                        return Err("resting order quantity is invalid");
                    }
                    total = total
                        .checked_add(order.remaining)
                        .ok_or("price level quantity overflows")?;
                    if expected.insert(order.id, (side, price)).is_some() {
                        return Err("resting order id is duplicated");
                    }
                }
            }
        }
        if expected != self.index {
            return Err("order index does not match resting orders");
        }
        if self
            .best_bid()
            .zip(self.best_ask())
            .is_some_and(|(bid, ask)| bid >= ask)
        {
            return Err("resting bids and asks cross");
        }
        Ok(())
    }

    /// The tick and lot this book enforces.
    #[must_use]
    pub fn rules(&self) -> MarketRules {
        self.rules
    }

    /// Set the tick and lot. The exchange does this when it assembles a
    /// book; nothing already resting is re-checked, because the rules a book
    /// is loaded with are the ones it was written with.
    pub fn set_rules(&mut self, rules: MarketRules) {
        self.rules = rules;
    }

    /// Validate an order without submitting it, against this book's rules.
    pub fn validate(&self, order: &Order) -> Result<(), OrderError> {
        Self::validate_with(order, self.rules)
    }

    /// Validate an order against `rules`, without a book to hand.
    pub fn validate_with(order: &Order, rules: MarketRules) -> Result<(), OrderError> {
        if order.qty == 0 {
            return Err(OrderError::ZeroQuantity);
        }
        if order.qty > MAX_ORDER_QTY {
            return Err(OrderError::QuantityTooLarge);
        }
        if !rules.allows_qty(order.qty) {
            return Err(OrderError::OddLot);
        }
        if let OrderKind::Limit { price_cents } = order.kind {
            if !(1..=MAX_PRICE_CENTS).contains(&price_cents) {
                return Err(OrderError::BadPrice);
            }
            if !rules.allows_price(price_cents) {
                return Err(OrderError::OffTick);
            }
        }
        Ok(())
    }

    /// Submit an order at `ts`: match it against the opposite side, then rest
    /// or drop the remainder according to its time in force.
    ///
    /// # Errors
    /// See [`OrderError`]. Synthetic owners are accepted here; the exchange
    /// is what forbids them.
    pub fn submit(&mut self, order: Order, ts: Timestamp) -> Result<Placement, OrderError> {
        self.validate(&order)?;
        let next = self.next_id.checked_add(1).ok_or(OrderError::IdExhausted)?;
        if self.next_id == 0 {
            return Err(OrderError::IdExhausted);
        }
        let id = OrderId(self.next_id);
        self.next_id = next;
        let limit = match order.kind {
            OrderKind::Market => None,
            OrderKind::Limit { price_cents } => Some(price_cents),
        };
        let mut trades = Vec::new();
        if order.tif == TimeInForce::Fok && self.available(order.side, limit, order.qty) < order.qty
        {
            return Ok(Placement {
                id,
                trades,
                filled: 0,
                remaining: order.qty,
                status: OrderStatus::Cancelled,
            });
        }
        let taker = Party {
            order: id,
            owner: order.owner,
        };
        let remaining = self.match_incoming(order.side, limit, order.qty, taker, ts, &mut trades);
        let filled = order.qty - remaining;
        let status = if remaining == 0 {
            OrderStatus::Filled
        } else if let (Some(price_cents), TimeInForce::Gtc) = (limit, order.tif) {
            self.rest(Resting {
                id,
                owner: order.owner,
                side: order.side,
                price_cents,
                qty: order.qty,
                remaining,
                ts,
            });
            OrderStatus::Resting
        } else {
            OrderStatus::Cancelled
        };
        Ok(Placement {
            id,
            trades,
            filled,
            remaining,
            status,
        })
    }

    /// Cancel a resting order.
    pub fn cancel(&mut self, id: OrderId) -> Option<Resting> {
        let (side, price) = self.index.remove(&id)?;
        let book = self.side_mut(side);
        let level = book.get_mut(&price)?;
        let pos = level.iter().position(|o| o.id == id)?;
        let order = level.remove(pos)?;
        if level.is_empty() {
            book.remove(&price);
        }
        Some(order)
    }

    /// Cancel every resting order of `owner`; returns them, best price first
    /// on each side, bids before asks.
    pub fn cancel_all(&mut self, owner: Owner) -> Vec<Resting> {
        let mut out = Vec::new();
        for (side, book) in [(Side::Buy, &mut self.bids), (Side::Sell, &mut self.asks)] {
            let mut empty = Vec::new();
            let iter: Box<dyn Iterator<Item = (&i64, &mut VecDeque<Resting>)>> = match side {
                Side::Buy => Box::new(book.iter_mut().rev()),
                Side::Sell => Box::new(book.iter_mut()),
            };
            for (&price, level) in iter {
                level.retain(|o| {
                    if o.owner == owner {
                        out.push(*o);
                        false
                    } else {
                        true
                    }
                });
                if level.is_empty() {
                    empty.push(price);
                }
            }
            for p in empty {
                book.remove(&p);
            }
        }
        for o in &out {
            self.index.remove(&o.id);
        }
        out
    }

    /// A resting order by id.
    #[must_use]
    pub fn get(&self, id: OrderId) -> Option<&Resting> {
        let &(side, price) = self.index.get(&id)?;
        self.side(side).get(&price)?.iter().find(|o| o.id == id)
    }

    /// Best bid price.
    #[must_use]
    pub fn best_bid(&self) -> Option<i64> {
        self.bids.last_key_value().map(|(&p, _)| p)
    }

    /// Best ask price.
    #[must_use]
    pub fn best_ask(&self) -> Option<i64> {
        self.asks.first_key_value().map(|(&p, _)| p)
    }

    /// Midpoint of the best bid and ask, if both exist.
    #[must_use]
    pub fn mid_cents(&self) -> Option<f64> {
        Some((self.best_bid()? as f64 + self.best_ask()? as f64) / 2.0)
    }

    /// Aggregated depth on `side`, best price first, at most `levels` deep.
    #[must_use]
    pub fn depth(&self, side: Side, levels: usize) -> Vec<Level> {
        let agg = |(&price_cents, level): (&i64, &VecDeque<Resting>)| Level {
            price_cents,
            qty: level.iter().map(|o| o.remaining).sum(),
            orders: u32::try_from(level.len()).unwrap_or(u32::MAX),
        };
        match side {
            Side::Buy => self.bids.iter().rev().take(levels).map(agg).collect(),
            Side::Sell => self.asks.iter().take(levels).map(agg).collect(),
        }
    }

    /// Every resting order: bids best-first, then asks best-first, FIFO
    /// within a price.
    pub fn orders(&self) -> impl Iterator<Item = &Resting> + '_ {
        self.bids
            .iter()
            .rev()
            .chain(self.asks.iter())
            .flat_map(|(_, level)| level.iter())
    }

    /// Resting orders of one owner, in [`orders`](Self::orders) order.
    pub fn orders_of(&self, owner: Owner) -> impl Iterator<Item = &Resting> + '_ {
        self.orders().filter(move |o| o.owner == owner)
    }

    /// Number of resting orders.
    #[must_use]
    pub fn len(&self) -> usize {
        self.index.len()
    }

    /// Whether nothing rests.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.index.is_empty()
    }

    /// What a `side` order for `qty` shares with an optional limit would
    /// execute right now, without changing anything.
    #[must_use]
    pub fn preview(&self, side: Side, qty: u64, limit: Option<i64>) -> Preview {
        let mut p = Preview::default();
        let mut left = qty;
        self.walk(side, limit, |price, level_qty| {
            let q = left.min(level_qty);
            left -= q;
            p.filled += q;
            p.notional_cents = p.notional_cents.saturating_add(notional(price, q));
            p.worst_price_cents = Some(price);
            left > 0
        });
        p
    }

    /// Shares available to a `side` order within `limit`, capped at `cap`.
    fn available(&self, side: Side, limit: Option<i64>, cap: u64) -> u64 {
        let mut total = 0u64;
        self.walk(side, limit, |_, level_qty| {
            total = total.saturating_add(level_qty);
            total < cap
        });
        total.min(cap)
    }

    /// Visit the opposite side's levels that a `side` order with `limit`
    /// crosses, best first, until `f` returns `false`.
    fn walk(&self, side: Side, limit: Option<i64>, mut f: impl FnMut(i64, u64) -> bool) {
        let levels: Box<dyn Iterator<Item = (&i64, &VecDeque<Resting>)>> = match side {
            Side::Buy => Box::new(self.asks.iter()),
            Side::Sell => Box::new(self.bids.iter().rev()),
        };
        for (&price, level) in levels {
            if !crosses(side, price, limit) {
                break;
            }
            let qty = level.iter().map(|o| o.remaining).sum();
            if !f(price, qty) {
                break;
            }
        }
    }

    fn match_incoming(
        &mut self,
        side: Side,
        limit: Option<i64>,
        mut qty: u64,
        taker: Party,
        ts: Timestamp,
        out: &mut Vec<Trade>,
    ) -> u64 {
        while qty > 0 {
            let opposite = self.side_mut(side.opposite());
            let Some((&price, level)) = (match side {
                Side::Buy => opposite.iter_mut().next(),
                Side::Sell => opposite.iter_mut().next_back(),
            }) else {
                break;
            };
            if !crosses(side, price, limit) {
                break;
            }
            let mut done_ids = Vec::new();
            while qty > 0 {
                let Some(front) = level.front_mut() else {
                    break;
                };
                let q = qty.min(front.remaining);
                front.remaining -= q;
                qty -= q;
                out.push(Trade {
                    ts,
                    price_cents: price,
                    qty: q,
                    taker_side: side,
                    taker,
                    maker: Party {
                        order: front.id,
                        owner: front.owner,
                    },
                });
                if front.remaining == 0 {
                    done_ids.push(front.id);
                    level.pop_front();
                }
            }
            let empty = level.is_empty();
            if empty {
                opposite.remove(&price);
            }
            for id in done_ids {
                self.index.remove(&id);
            }
        }
        qty
    }

    fn rest(&mut self, order: Resting) {
        self.index.insert(order.id, (order.side, order.price_cents));
        self.side_mut(order.side)
            .entry(order.price_cents)
            .or_default()
            .push_back(order);
    }

    const fn side(&self, side: Side) -> &BTreeMap<i64, VecDeque<Resting>> {
        match side {
            Side::Buy => &self.bids,
            Side::Sell => &self.asks,
        }
    }

    const fn side_mut(&mut self, side: Side) -> &mut BTreeMap<i64, VecDeque<Resting>> {
        match side {
            Side::Buy => &mut self.bids,
            Side::Sell => &mut self.asks,
        }
    }
}

/// Whether a `side` order with `limit` may trade at the opposite price.
const fn crosses(side: Side, price: i64, limit: Option<i64>) -> bool {
    match (side, limit) {
        (_, None) => true,
        (Side::Buy, Some(l)) => price <= l,
        (Side::Sell, Some(l)) => price >= l,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloc::vec;

    const T: TraderId = TraderId(1);
    const U: TraderId = TraderId(2);

    fn book_with_ladder() -> OrderBook {
        let mut b = OrderBook::new();
        for k in 0..3 {
            b.submit(
                Order::limit(Owner::Synthetic, Side::Buy, 9_900 - k * 10, 100),
                Timestamp(0),
            )
            .unwrap();
            b.submit(
                Order::limit(Owner::Synthetic, Side::Sell, 10_100 + k * 10, 100),
                Timestamp(0),
            )
            .unwrap();
        }
        b
    }

    #[test]
    fn price_time_priority_and_partial_fills() {
        let mut b = book_with_ladder();
        assert_eq!((b.best_bid(), b.best_ask()), (Some(9_900), Some(10_100)));
        // Two traders queue at the same price; the earlier one fills first.
        let a = b
            .submit(
                Order::limit(Owner::Trader(T), Side::Buy, 10_000, 50),
                Timestamp(1),
            )
            .unwrap();
        let c = b
            .submit(
                Order::limit(Owner::Trader(U), Side::Buy, 10_000, 50),
                Timestamp(2),
            )
            .unwrap();
        assert_eq!(a.status, OrderStatus::Resting);
        assert_eq!(b.best_bid(), Some(10_000));
        let sell = b
            .submit(
                Order::market(Owner::Synthetic, Side::Sell, 70),
                Timestamp(3),
            )
            .unwrap();
        assert_eq!(sell.filled, 70);
        assert_eq!(sell.trades.len(), 2);
        assert_eq!(sell.trades[0].maker.order, a.id);
        assert_eq!(sell.trades[0].qty, 50);
        assert_eq!(sell.trades[1].maker.order, c.id);
        assert_eq!(sell.trades[1].qty, 20);
        assert_eq!(b.get(c.id).unwrap().remaining, 30);
        assert!(b.get(a.id).is_none());
        // Market buy sweeps two levels and cancels the rest.
        let buy = b
            .submit(
                Order::market(Owner::Trader(T), Side::Buy, 250),
                Timestamp(4),
            )
            .unwrap();
        assert_eq!(buy.filled, 250);
        assert_eq!(
            buy.trades.iter().map(|t| t.price_cents).collect::<Vec<_>>(),
            [10_100, 10_110, 10_120]
        );
        let big = b
            .submit(
                Order::market(Owner::Trader(T), Side::Buy, 100),
                Timestamp(5),
            )
            .unwrap();
        assert_eq!(
            (big.filled, big.remaining, big.status),
            (50, 50, OrderStatus::Cancelled)
        );
        assert_eq!(b.best_ask(), None);
    }

    #[test]
    fn ioc_fok_cancel_and_depth() {
        let mut b = book_with_ladder();
        let ioc = b
            .submit(
                Order::limit(Owner::Trader(T), Side::Buy, 10_105, 150).with_tif(TimeInForce::Ioc),
                Timestamp(1),
            )
            .unwrap();
        assert_eq!((ioc.filled, ioc.status), (100, OrderStatus::Cancelled));
        assert!(b.get(ioc.id).is_none());
        let fok = b
            .submit(
                Order::limit(Owner::Trader(T), Side::Buy, 10_115, 150).with_tif(TimeInForce::Fok),
                Timestamp(2),
            )
            .unwrap();
        assert_eq!((fok.filled, fok.status), (0, OrderStatus::Cancelled));
        let fok = b
            .submit(
                Order::limit(Owner::Trader(T), Side::Buy, 10_120, 150).with_tif(TimeInForce::Fok),
                Timestamp(3),
            )
            .unwrap();
        assert_eq!((fok.filled, fok.status), (150, OrderStatus::Filled));
        let r = b
            .submit(
                Order::limit(Owner::Trader(T), Side::Sell, 10_050, 10),
                Timestamp(4),
            )
            .unwrap();
        assert_eq!(
            b.depth(Side::Sell, 5),
            vec![
                Level {
                    price_cents: 10_050,
                    qty: 10,
                    orders: 1
                },
                Level {
                    price_cents: 10_120,
                    qty: 50,
                    orders: 1
                },
            ]
        );
        assert_eq!(b.cancel(r.id).unwrap().remaining, 10);
        assert!(b.cancel(r.id).is_none());
        assert_eq!(b.cancel_all(Owner::Synthetic).len(), 4);
        assert!(b.is_empty());
    }

    #[test]
    fn preview_matches_execution() {
        let mut b = book_with_ladder();
        let p = b.preview(Side::Sell, 250, None);
        assert_eq!(p.filled, 250);
        assert_eq!(p.notional_cents, 100 * 9_900 + 100 * 9_890 + 50 * 9_880);
        assert_eq!(p.worst_price_cents, Some(9_880));
        let done = b
            .submit(
                Order::market(Owner::Trader(T), Side::Sell, 250),
                Timestamp(0),
            )
            .unwrap();
        assert_eq!(done.notional_cents(), p.notional_cents);
        assert_eq!(b.preview(Side::Sell, 10, Some(9_885)).filled, 0);
    }

    #[test]
    fn state_validation_detects_corrupted_books() {
        let good = book_with_ladder();
        assert_eq!(good.validate_state(), Ok(()));
        let mut bad = good.clone();
        bad.index.clear();
        assert!(bad.validate_state().is_err());
        let mut bad = good.clone();
        bad.next_id = 1;
        assert!(bad.validate_state().is_err());
        let mut bad = good.clone();
        bad.bids.first_entry().unwrap().get_mut()[0].remaining = 0;
        assert!(bad.validate_state().is_err());
        let mut bad = good.clone();
        bad.asks.first_entry().unwrap().get_mut()[0].side = Side::Buy;
        assert!(bad.validate_state().is_err());
        let mut bad = good.clone();
        bad.asks.insert(12345, VecDeque::new());
        assert!(bad.validate_state().is_err());
        let mut book = good;
        book.submit(
            Order::market(Owner::Trader(T), Side::Buy, 125),
            Timestamp(1),
        )
        .unwrap();
        assert_eq!(book.validate_state(), Ok(()));
        book.cancel_all(Owner::Synthetic);
        assert_eq!(book.validate_state(), Ok(()));
    }

    #[test]
    fn advancing_ids_preserves_existing_orders_and_never_rewinds() {
        let mut book = book_with_ladder();
        let depth = book.depth(Side::Buy, 10);
        book.advance_order_id(OrderId(100));
        book.advance_order_id(OrderId(2));
        assert_eq!(book.next_order_id(), OrderId(100));
        assert_eq!(book.depth(Side::Buy, 10), depth);
        let result = book
            .submit(Order::market(Owner::Trader(T), Side::Buy, 1), Timestamp(0))
            .unwrap();
        assert_eq!(result.id, OrderId(100));
        assert_eq!(book.validate_state(), Ok(()));
    }

    #[test]
    fn exhausted_ids_reject_orders_without_mutating_the_book() {
        let mut book = book_with_ladder();
        book.next_id = u64::MAX;
        let before = book.clone();
        assert_eq!(
            book.submit(Order::market(Owner::Trader(T), Side::Buy, 1), Timestamp(0)),
            Err(OrderError::IdExhausted)
        );
        assert_eq!(book, before);
    }

    #[test]
    fn default_book_never_assigns_the_hidden_order_id() {
        let mut book = OrderBook::default();
        assert_eq!(book, OrderBook::new());
        let placed = book
            .submit(
                Order::limit(Owner::Trader(T), Side::Buy, 100, 1),
                Timestamp(0),
            )
            .unwrap();
        assert_eq!(placed.id, OrderId(1));
        assert_ne!(placed.id, OrderId::HIDDEN);
        assert_eq!(book.cancel(placed.id).unwrap().id, placed.id);
    }

    #[test]
    fn rejects_bad_orders() {
        let mut b = OrderBook::new();
        let bad = Order::limit(Owner::Trader(T), Side::Buy, 0, 1);
        assert_eq!(b.submit(bad, Timestamp(0)), Err(OrderError::BadPrice));
        let bad = Order::market(Owner::Trader(T), Side::Buy, 0);
        assert_eq!(b.submit(bad, Timestamp(0)), Err(OrderError::ZeroQuantity));
        // A GTC market order into an empty book is simply cancelled.
        let m = b
            .submit(
                Order::market(Owner::Trader(T), Side::Buy, 5).with_tif(TimeInForce::Gtc),
                Timestamp(0),
            )
            .unwrap();
        assert_eq!(m.status, OrderStatus::Cancelled);
        assert!(b.is_empty());
    }
}
